### ISSUE TITLE
Bloodlines Dependency Issue

### ISSUE THREAD

**Issue by yuderekyu** [yuderekyu/covenant#9]
Currently, when building any Expresso microservice, I receive this error: 
># github.com/ghmeier/bloodlines/handlers
>..\..\ghmeier\bloodlines\handlers\handlers.go:123: cannot use cors.New(config) >(type "github.com/gin-gonic/gin".HandlerFunc) as type >"gopkg.in/gin-gonic/gin.v1".HandlerFunc in return argument

Seems related to this issue: https://github.com/gin-gonic/gin/issues/794

**Comment by ghmeier** [comment]
are you using 'github.com/gin-gonic/gin' anywhere? seems like that could cause the issue?

**Comment by yuderekyu** [comment]
I'm not importing `github.com/gin-gonic/gin` in any file, but interestingly it's within covenant's `Godeps.json` . I went ahead and deleted it, but I'm still getting the error :/ Looking more into it

**Comment by yuderekyu** [comment]
Fixed by reverting `gopkg.in/gin-contrib/cors.v1` to commit `fb918bcd825b9e20f0c3c365981baf9454029b6c`
